export const LOAD_METRICS_REQUESTED = "LOAD_METRICS_REQUESTED";
export const LOAD_METRICS_SUCCESS = "LOAD_METRICS_SUCCESS";
export const LOAD_METRICS_FAILED = "LOAD_METRICS_FAILED";

export const METRIC_FILTER_STARTDATE_CHANGED = "METRIC_FILTER_STARTDATE_CHANGED";
export const METRIC_FILTER_ENDDATE_CHANGED = "METRIC_FILTER_ENDDATE_CHANGED";
export const METRIC_FILTER_PRIMARY_METRIC_CHANGED = "METRIC_FILTER_PRIMARY_METRIC_CHANGED";
export const METRIC_FILTER_SECONDARY_METRIC_CHANGED = "METRIC_FILTER_SECONDARY_METRIC_CHANGED";